apiVersion: v1
kind: Service
metadata:
  name: k8s-dashboard-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: NodePort
  selector:
    app: k8s-dashboard        
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
